In [1]:
import numpy as np


# creating ndarrays
1. np.array()
2.np.zeros(), np.empty(),np.ones()
 zeros and ones create arrays of 0’s or 1’s, respectively, with a given length
or shape. empty creates an array without initializing its values to any particular value.
To create a higher dimensional array with these methods, pass a tuple for the shape:

In [2]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
arr1.ndim

1

In [4]:
arr1.shape

(5,)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
#Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2=[[1,2,3,4],[5,6,7,8]]
arr2= np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int64')

In [10]:
data3=[[1,2.7,3,4],[5,6,7,8]]
arr3= np.array(data3)
arr3

array([[1. , 2.7, 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [11]:
arr3.ndim

2

In [12]:
arr3.shape

(2, 4)

In [13]:
arr3.dtype

dtype('float64')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2,3,2)) # 2 block 3 rows and 2 column(3D)

array([[[1.12497210e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23053953e-307, 8.97773909e-067]],

       [[2.06032101e+184, 4.03410988e+175],
        [8.93158961e+165, 1.00427284e-042],
        [3.37736461e-057, 5.49842285e+170]]])

In [17]:
np.arange(15) # 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# typecasting 
by (astype() method)
we can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:

Calling astype always creates a new array (a copy of the data), even if
the new dtype is the same as the old dtype.

In [18]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [19]:
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [20]:
float_arr1= arr3.astype(np.int32)
float_arr1.dtype

dtype('int32')

In [21]:
arr = np.array([1.4,-2.9,0.3,8.4])
arr
arr.astype(np.int32)

array([ 1, -2,  0,  8], dtype=int32)

In [22]:
numeric_strings = np.array(['1.25', '-9.6', '4.2'], dtype=np.bytes_)
numeric_strings=numeric_strings.astype(float)
numeric_strings

array([ 1.25, -9.6 ,  4.2 ])

In [23]:
arr5= np.array([1.4,-2.9,0.3,8.4])
arr5
arr5.astype(np.bytes_)

array([b'1.4', b'-2.9', b'0.3', b'8.4'], dtype='|S32')

In [24]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([      0,       1,       0, 5570652,     892,       0,     768,
           530], dtype=uint32)

# Operations between Arrays and Scalars
1. Operations between differently sized arrays is called broadcasting

In [26]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr*arr #square

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [28]:
arr-arr # subtraction

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
arr**0.5 # squareroot

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [30]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

# Basic Indexing and Slicing

In [32]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr[1]

np.int64(1)

In [34]:
arr[2:9]# last digit excluded

array([2, 3, 4, 5, 6, 7, 8])

In [35]:
arr_slice=arr[5:8] # on 6 place 12345 willbe because 5 will treat as 0 and 1 will be on 6
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9,    10,    11,    12,    13,    14])

In [37]:
arr_slice[:]=64 #arr_slice is 5 to 8 but 8 will excluded so on 5,6,7 there will be 64 value
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10, 11, 12, 13, 14])