In [67]:
import numpy as np
from numpy.random import randn

# Storing Arrays on Disk in Binary Format

**np.save** and **np.load** are the two workhorse functions for efficiently saving and loading
array data on disk. Arrays are saved by default in an uncompressed raw binary format
with file extension .npy.

In [68]:
arr=np.arange(10)
np.save('some_array',arr)

In [69]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You save multiple arrays in a zip archive using **np.savez** and passing the arrays as key
word arguments:

In [70]:
np.savez('array_archive.npz',a=arr,b=arr)

In [71]:
arch = np.load('array_archive.npz')

In [72]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Saving and Loading Text Files

# Linear Algebra

Linear algebra, like matrix multiplication, decompositions, determinants, and other
square matrix math, is an important part of any array library. Unlike some languages
like MATLAB, multiplying two two-dimensional arrays with * is an element-wise
product instead of a matrix dot product. As such, there is a function dot, both an array
method, and a function in the numpy namespace, for matrix multiplication:

In [73]:
x=np.array([[1.,2.,3.],[4.,5.,6.,]])
y=np.array([[7.,23.],[4.,5],[6.,8]])

In [74]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [75]:
y

array([[ 7., 23.],
       [ 4.,  5.],
       [ 6.,  8.]])

In [76]:
x.dot(y) # # equivalently np.dot(x, y)

array([[ 33.,  57.],
       [ 84., 165.]])

In [77]:
np.dot(x,np.ones(3))

array([ 6., 15.])

numpy.linalg has a standard set of matrix decompositions and things like inverse and
determinant.

In [78]:
from numpy.linalg import inv, qr

In [79]:
X=randn(5,5)
mat=X.T.dot(X)

In [80]:
inv(mat)

array([[ 1.98477716, -0.67750479, -1.1932869 ,  0.32321471, -1.94049737],
       [-0.67750479,  1.63237204,  0.50239743, -0.40580367,  2.16540758],
       [-1.1932869 ,  0.50239743,  0.82837352, -0.13999829,  1.31199242],
       [ 0.32321471, -0.40580367, -0.13999829,  0.58746295, -0.71884479],
       [-1.94049737,  2.16540758,  1.31199242, -0.71884479,  3.72810752]])

In [81]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -5.66610008e-16,  3.65039511e-16,
        -4.08229135e-16, -2.20042528e-15],
       [ 1.66728751e-15,  1.00000000e+00, -1.42616829e-15,
         7.38594768e-16, -3.58700259e-15],
       [ 8.91482024e-16,  1.37540446e-17,  1.00000000e+00,
        -4.35959390e-16, -3.06026466e-15],
       [-1.50510041e-16,  1.15575403e-17,  1.23106046e-16,
         1.00000000e+00,  4.78398070e-16],
       [-1.51294186e-15,  9.81106353e-16,  1.24791450e-15,
        -1.13107941e-16,  1.00000000e+00]])

In [82]:
q,r=qr(mat)
r

array([[ -7.65306563,   1.78314827, -11.87927358,   2.23402514,
         -0.45623498],
       [  0.        ,  -9.12703285,  -9.10503582,   3.07558168,
          9.259105  ],
       [  0.        ,   0.        ,  -1.61300557,   0.8686007 ,
          0.79121183],
       [  0.        ,   0.        ,   0.        ,  -2.1473515 ,
         -0.41842905],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.20165484]])

In [83]:
q

array([[-0.61494731,  0.07533276,  0.67017845,  0.11790488, -0.39131069],
       [ 0.23312315, -0.67140599,  0.5504449 , -0.03466632,  0.43666493],
       [-0.72366011, -0.41046904, -0.41970978, -0.2483502 ,  0.26456963],
       [ 0.10625565,  0.12940382,  0.16733025, -0.96070391, -0.14495853],
       [-0.18033074,  0.598589  ,  0.20908263, -0.01633606,  0.75179094]])

**Commonly-used numpy.linalg functions**
* diag:Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square
    matrix with zeros on the off-diagonal
* dot: Matrix multiplication
* trace:Compute the sum of the diagonal elements
* det:Compute the matrix determinant
* eig:Compute the eigenvalues and eigenvectors of a square matrix
* inv:Compute the inverse of a square matrix
* pinv:Compute the Moore-Penrose pseudo-inverse inverse of a square matrix
* qr:Compute the QR decomposition
* svd:Compute the singular value decomposition (SVD)
* solve:Solve the linear system Ax = b for x, where A is a square matrix
* lstsq: Compute the least-squares solution to y = Xb

# Random Number Generation

The numpy.random module supplements the built-in Python random with functions for
efficiently generating whole arrays of sample values from many kinds of probability distributions. For example, you can get a 4 by 4 array of samples from the standard
normal distribution using normal:

In [84]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 0.59770623, -0.01919017, -0.20870615,  1.61418095],
       [ 0.13539935, -0.18995132, -1.21563483,  0.86867064],
       [-0.59512265,  0.64855823,  0.23836325, -0.32954886],
       [-0.07797769,  0.38707215, -0.93264399,  1.24847727]])

In [85]:
# module to generate random floating-point numbers that follow a normal (Gaussian) distribution (a bell curve)
from random import normalvariate

In [86]:
N =1000000

In [87]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

1.5 s ± 74.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [88]:
 %timeit np.random.normal(size=N)

66.7 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


**Partial list of numpy.random functions**
* seed: Seed the random number generator
* permutation : Return a random permutation of a sequence, or return a permuted range
* shuffle: Randomly permute a sequence in place
* rand : Draw samples from a uniform distribution
* randint:Draw random integers from a given low-to-high range
* randn:Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)
* binomial: Draw samples a binomial distribution
* normal:Draw samples from a normal (Gaussian) distribution
* beta: Draw samples from a beta distribution
* chisquare:Draw samples from a chi-square distribution
* gamma: Draw samples from a gamma distribution
* uniform: Draw samples from a uniform [0, 1) distribution
