# comand for importing

In [60]:
import numpy as np

# Basic Indexing and Slicing

## slicing concept

In [61]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
arr[1]

np.int64(1)

In [63]:
arr[2:9]# last digit excluded

array([2, 3, 4, 5, 6, 7, 8])

In [64]:
arr_slice=arr[5:8] # on 6 place 12345 willbe because 5 will treat as 0 and 1 will be on 6
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9,    10,    11,    12,    13,    14])

In [65]:
arr_slice[:]=64 #arr_slice is 5 to 8 but 8 will excluded so on 5,6,7 there will be 64 value
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10, 11, 12, 13, 14])

In [66]:
# 2d

In [67]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[2]

array([7, 8, 9])

In [69]:
arr2d[1]

array([4, 5, 6])

In [70]:
arr2d[0][2]

np.int64(3)

In [71]:
arr2d[0,2]

np.int64(3)

In [72]:
# 3d

In [73]:
arr3d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [76]:
arr3d[0,1,2]

np.int64(6)

In [77]:
old=arr3d[0].copy()

In [78]:
arr3d[0]=32
arr3d

array([[[32, 32, 32],
        [32, 32, 32]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0]=old
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# boolean indexing

In [80]:
from numpy.random import randn

In [81]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [82]:
data=randn(7,4)
data

array([[ 1.17160778,  1.03936606,  0.35188761,  1.0566837 ],
       [-0.2778747 , -0.87897141,  0.27420256, -1.79194946],
       [-1.34049333,  0.00921198, -0.44367763, -0.66741849],
       [ 0.5714329 ,  0.69260634, -0.11025471,  1.56262361],
       [-1.1924321 , -0.82916828,  1.25897809,  0.96525069],
       [ 0.61945199, -0.21514637,  1.46990876,  0.66540457],
       [-0.65520389,  0.73088119, -1.4188679 , -1.0458523 ]])

In [83]:
names =='Bob' # equal 

array([ True, False, False,  True, False, False, False])

In [84]:
data1=data.copy()

In [85]:
data[names =='Bob'] # as bob is in Row[0] and Row[3] so it just return the rows from data 

array([[ 1.17160778,  1.03936606,  0.35188761,  1.0566837 ],
       [ 0.5714329 ,  0.69260634, -0.11025471,  1.56262361]])

In [86]:
 data[names == 'Bob', 2:]

array([[ 0.35188761,  1.0566837 ],
       [-0.11025471,  1.56262361]])

In [87]:
 data[names == 'Bob', 3:]

array([[1.0566837 ],
       [1.56262361]])

In [88]:
names !='Bob' # not equal

array([False,  True,  True, False,  True,  True,  True])

In [89]:
data[~(names == 'Bob')]

array([[-0.2778747 , -0.87897141,  0.27420256, -1.79194946],
       [-1.34049333,  0.00921198, -0.44367763, -0.66741849],
       [-1.1924321 , -0.82916828,  1.25897809,  0.96525069],
       [ 0.61945199, -0.21514637,  1.46990876,  0.66540457],
       [-0.65520389,  0.73088119, -1.4188679 , -1.0458523 ]])

In [90]:
mask=(names=='Bob')|(names=='Joe') 
mask

array([ True,  True, False,  True, False,  True,  True])

In [91]:
data1[mask]

array([[ 1.17160778,  1.03936606,  0.35188761,  1.0566837 ],
       [-0.2778747 , -0.87897141,  0.27420256, -1.79194946],
       [ 0.5714329 ,  0.69260634, -0.11025471,  1.56262361],
       [ 0.61945199, -0.21514637,  1.46990876,  0.66540457],
       [-0.65520389,  0.73088119, -1.4188679 , -1.0458523 ]])

In [92]:
data[data < 0] = 0
data

array([[1.17160778, 1.03936606, 0.35188761, 1.0566837 ],
       [0.        , 0.        , 0.27420256, 0.        ],
       [0.        , 0.00921198, 0.        , 0.        ],
       [0.5714329 , 0.69260634, 0.        , 1.56262361],
       [0.        , 0.        , 1.25897809, 0.96525069],
       [0.61945199, 0.        , 1.46990876, 0.66540457],
       [0.        , 0.73088119, 0.        , 0.        ]])

In [93]:
data[names!='Joe']=1
data

array([[1.        , 1.        , 1.        , 1.        ],
       [0.        , 0.        , 0.27420256, 0.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [0.61945199, 0.        , 1.46990876, 0.66540457],
       [0.        , 0.73088119, 0.        , 0.        ]])

# Fancy Indexing

In [94]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [95]:
arr[[4,3,0,6]] # return the value of these indexes

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [96]:
arr[[1,2,7]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [7., 7., 7., 7.]])

In [97]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

arr=np.arange(32).reshape((8,4))
arr

In [98]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # return value like on 1 row and 0 column(1,0): 4 (5,3): 23

array([1., 5., 7., 2.])

In [99]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [100]:
 arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

# Transposing Arrays and Swapping Axes

(.T): transpose
(.swapaxes): swapping

In [101]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

 ## DOT method: np.dot X^TX

In [103]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [104]:
arr=np.random.randn(6,3)
arr

array([[ 0.71927   ,  0.97474976,  0.96251111],
       [ 0.46242194, -0.53730578,  0.81046911],
       [ 0.67976609,  0.72688678, -0.98854109],
       [ 0.55522612,  0.433852  ,  0.60545682],
       [-0.86247651,  0.05177937, -2.28644678],
       [-0.49253241, -0.78669856, -0.57820447]])

In [105]:
np.dot(arr.T,arr)

array([[2.48799525, 1.53046127, 2.98806386],
       [1.53046127, 2.57700227, 0.38334079],
       [2.98806386, 0.38334079, 8.48923855]])

In [106]:
arr = np.arange(16).reshape((2, 2, 4))
arr
#Generates numbers 0 through 15.Groups them into a shape of (2, 2, 4): 2 blocks, 2 rows per block, and 4 columns per row.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [107]:
arr.transpose((1,0,2)) # NumPy redefines the physical dimensions—specifically swapping the "Block" dimension with the "Row" dimension while leaving the "Column" dimension completely untouched.

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [108]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [109]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# Universal Functions: Fast Element-wise Array Functions

In [110]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [112]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [113]:
x=randn(8)
x

array([ 0.95971069, -0.02453634,  1.19347243, -1.30563296, -0.00619626,
        0.22878997,  0.11585747,  1.97780094])

In [114]:
y=randn(8)
y

array([-0.17735659,  0.27196771, -0.51962593, -0.83697939, -0.62658038,
        0.22453998,  0.51426733,  0.11517383])

In [115]:
np.maximum(x,y) # return element wise

array([ 0.95971069,  0.27196771,  1.19347243, -0.83697939, -0.00619626,
        0.22878997,  0.51426733,  1.97780094])

In [116]:
arr= randn(7)*2
arr

array([ 1.72852926,  0.02970557, -1.36706119, -1.22425804,  0.85343828,
        0.39168691,  3.39828109])

While not common, a ufunc can return multiple arrays. modf is one example, a vector
ized version of the built-in Python divmod: it returns the fractional and integral parts of
a floating point array:

In [117]:
np.modf(arr)

(array([ 0.72852926,  0.02970557, -0.36706119, -0.22425804,  0.85343828,
         0.39168691,  0.39828109]),
 array([ 1.,  0., -1., -1.,  0.,  0.,  3.]))

# Unary ufuncs

* abs, fabs: Compute the absolute value element-wise for integer, floating point, or complex values.
      Use fabs as a faster alternative for non-complex-valued data

* sqrt: Compute the square root of each element. Equivalent to arr ** 0.5

* square: Compute the square of each element. Equivalent to arr ** 2

* exp: Compute the exponent ex of each element

* log, log10, log2, log1p: Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively

* sign: Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)

* ceil: Compute the ceiling of each element, i.e. the smallest integer greater than or equal to each element

* floor: Compute the floor of each element, i.e. the largest integer less than or equal to eachelement

  
* rint: Round elements to the nearest integer, preserving the dtype

  
* modf:Return fractional and integral parts of array as separate array


* isnan: Return boolean array indicating whether each value is NaN (Not a Number)

* isfinite,isinf: Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively

* cos, cosh, sin, sinh,tan, tanh: Regular and hyperbolic trigonometric functions

* arccos, arccosh, arcsin,arcsinh, arctan, arctanh:Inverse trigonometric functions

* logical_not: Compute truth value of not x element-wise. Equivalent to -arr.

#  Binary universal functions

* add:Add corresponding elements in arrays
* subtract:Subtract elements in second array from first array
* multiply:Multiply array elements
* divide, floor_divide:Divide or floor divide (truncating the remainder)
* power:Raise elements in first array to powers indicated in second array
* maximum, fmax:Element-wise maximum. fmax ignores NaN
* minimum, fmin:Element-wise minimum. fmin ignores NaN
* mod: Element-wise modulus (remainder of division)
* copysign:Copy sign of values in second argument to values in first argument
* greater, greater_equal,less, less_equal, equal,not_equal:Perform element-wise comparison, yielding boolean array. Equivalent to infix operators
         >, >=, <, <=, ==, !=
* logical_and,logical_or, logical_xor: Compute element-wise truth value of logical operation. Equivalent to infix operators &
      |, ^



